spring.application.name=customer_service

logging.level.org.springframework=ERROR
logging.level.com=TRACE

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=humber

server.port=9091

eureka.client.serviceUrl.defaultZone=http://${registry.host:localhost}:${registry.port:8761}/eureka/

spring.cloud.discovery.enabled=true
spring.profiles.active=dev

management.endpoints.web.exposure.include=*
